robot_initial_positions:
  group_states:
    arm:
      Revolute 1: 3.14
      Revolute 2: 0.0
      Revolute 3: 0.0
      Revolute 4: 0.0
    gripper:
      Revolute 6: 0.0
      Revolute 7: 0.0
      Revolute 8: 0.0
      Revolute 9: 0.0
